### ISSUE TITLE
Add requests 2.29.0 to requirements.txt

### ISSUE THREAD

**Issue by stlozhaw** [sustainability-zhaw/ad-resolver#10]

**Comment by phish108** [comment]
I merged the PR. 

But: pinning an old version makes me feel a bit odd. 

Is upstream aware of this situation and, if yes, are there any remarks about fixes?

**Comment by stlozhaw** [comment]
> I merged the PR.
> 
> But: pinning an old version makes me feel a bit odd.
> 
> Is upstream aware of this situation and, if yes, are there any remarks about fixes?

I am not too happy about it. We are not directly depending on `requests` so there should not be a need to explicitly install it here or on the indexer.

See https://github.com/sustainability-zhaw/sdg-indexer/issues/7#issuecomment-1560589172
